# Generated by Django 4.2.17 on 2025-03-02 20:31

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PapStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("admin_access", "Can access admin"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
