# Generated by Django 4.2.17 on 2025-03-11 13:28

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papstats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVColumnMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100, unique=True)),
                ("mapped_to", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IgnoredCSVColumns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyFleetType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=10)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
            options={
                "unique_together": {("name", "source", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="UnknownAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyUserStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("corporation_id", models.PositiveIntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_fats", models.PositiveIntegerField()),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papstats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "month", "year", "fleet_type")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyCreatorStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator_id", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_created", models.IntegerField(default=0)),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papstats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("creator_id", "month", "year", "fleet_type")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyCorpStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corporation_id", models.PositiveIntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_fats", models.PositiveIntegerField()),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papstats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation_id", "month", "year", "fleet_type")},
            },
        ),
    ]
