# Generated by Django 4.2.17 on 2025-03-19 03:15

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "papstats",
            "0002_csvcolumnmapping_ignoredcsvcolumns_monthlyfleettype_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papstats",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("admin_access", "Can access admin"),
                    ("fc_access", "Can access fc"),
                    ("alliance_access", "Can access alliance"),
                ),
            },
        ),
    ]
